services:
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - esd-net
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong:3.5
    container_name: kong-migrations
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
    networks:
      - esd-net
    command: kong migrations bootstrap

  kong:
    image: kong:3.5
    container_name: kong
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml  
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_MANAGER_LISTEN: 0.0.0.0:8002
      KONG_PORTAL: "on"
      KONG_PORTAL_GUI_HOST: localhost:8002
    volumes:
    - ./kong.yml:/kong.yml
    networks:
      - esd-net
    ports:
      - "8000:8000" # Proxy (Frontend connects here)
      - "8443:8443" # Proxy SSL
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API SSL
      - "8002:8002" # Kong Manager UI (Web Interface)
